# Generated by Django 4.0 on 2022-12-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='movie',
            field=models.FileField(blank=True, upload_to='Images/'),
        ),
    ]
